### ISSUE TITLE
I have a question plz help thx

### ISSUE THREAD

**Issue by ghost** [im-minion/Flutter-Blog-App-Firebase#2]
Very nice project, thanks a lot. 

my question is after you logout and you want to login again, there is no google account choose option. I want to have the same choose screen like we login at the first time. How can you do that? Thank you.

**Comment by im-minion** [comment]
Thanks...:)
Isuue solved, Please check or pull new code :)

**Comment by ghost** [comment]
Working perfect thx bro

**Comment by shindesharad71** [comment]
Issue solved! Thank You!

**Comment by trungwebsite** [comment]
Could you add Category for it. Thanks ;)
